import { ColorThemeProvider } from "@/providers/ColorThemeProvider";
import { Potta_One } from "next/font/google";
import { M_PLUS_1p } from "next/font/google";
import "@/styles/styles.scss";
import type { Metadata } from "next";
import { Header } from "@/components/shared/Header";
import { Layout } from "@/components/shared/Layout";
import { Main } from "@/components/shared/Main";

const PottaOneFont = Potta_One({
	weight: "400",
	variable: "--font_potta_one",
	subsets: ["latin"],
});

const MPlus1pFont = M_PLUS_1p({
	weight: "400",
	variable: "--font_m_plus_1p",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja" suppressHydrationWarning>
			<head>
				<script
					// biome-ignore lint/security/noDangerouslySetInnerHtml: This is a script tag
					dangerouslySetInnerHTML={{
						__html: `!function(){const e=window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light",t=localStorage.getItem("okmkm-blog-color-theme"),o="system"===t||null==t?e:"light"===t?"light":"dark";window.document.documentElement.dataset.colorTheme=o}();`,
					}}
				/>
			</head>
			<body className={`${PottaOneFont.variable} ${MPlus1pFont.variable}`}>
				<ColorThemeProvider>
					<Layout>
						<Header />
						<Main>{children}</Main>
						<footer>footer</footer>
					</Layout>
				</ColorThemeProvider>
			</body>
		</html>
	);
}
