name: Blog App CI/CD Pipeline

# ワークフローのトリガー設定
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "contents-manager/articles/**"
      - "packages/**"
      - ".github/workflows/blog_cicd.yml"
  pull_request:
    branches:
      - main
    paths:
      - "app/**"
      - "contents-manager/articles/**"
      - "packages/**"
      - ".github/workflows/blog_cicd.yml"
  workflow_dispatch: # 手動実行用のトリガー

# 同時実行制御の設定
concurrency:
  # グループ名の定義 - PRの場合はPR番号、mainへのpushの場合は'production'とする
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || 'production' }}
  # 新しいワークフローの実行時に進行中のワークフローをキャンセル
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Biome check
        run: pnpm format:check

      - name: Type check app
        run: pnpm app typecheck

  cd:
    name: Build and Deploy
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    environment: Production
    env:
      API_BASE_URL: ${{ vars.API_BASE_URL }}
      BASE_URL: ${{ vars.BASE_URL }}
      PROJECT_NAME: okmkm-blog
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Start contents-manager API Server
        uses: ./.github/actions/start_contents_manager_api
        id: start_api

      - name: Build app
        run: pnpm app build

      - name: Stop contents-manager API Server
        uses: ./.github/actions/stop_contents_manager_api
        with:
          api_pid: ${{ steps.start_api.outputs.api_pid }}

      - name: Deploy and Comment
        uses: ./.github/actions/deploy_blog_app_to_cloudflare_pages
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project_name: ${{ env.PROJECT_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
