name: Monitor Zenn RSS

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  check-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download previous state
        id: download
        uses: dawidd6/action-download-artifact@v2
        with:
          name: zenn-rss-state
          workflow: monitor_zenn_rss.yml
          if_no_artifact_found: warn
          path: .github/scripts/zenn_rss_monitor

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run RSS checker
        id: check_rss
        run: |
          cd .github/scripts/zenn_rss_monitor
          go run check_zenn_rss.go

      - name: Upload state as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zenn-rss-state
          path: .github/scripts/zenn_rss_monitor/zenn_rss_state.json
          retention-days: 2

      - name: Build and deploy when changed
        if: steps.check_rss.outputs.has_changes == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ZENN_UPDATED_PAT }}
          event-type: zenn-feed-updated
